<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'Imagify\\Dependencies\\WPMedia\\PluginFamily\\' => array($vendorDir . '/wp-media/plugin-family/src'),
    'Imagify\\Dependencies\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Imagify\\Dependencies\\League\\Container\\' => array($vendorDir . '/league/container/src'),
);
