<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit6503970e5795e8c75f18db09788a0b40
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Imagify\Dependencies\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Imagify\Dependencies\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit6503970e5795e8c75f18db09788a0b40', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Imagify\Dependencies\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit6503970e5795e8c75f18db09788a0b40', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Imagify\Dependencies\Composer\Autoload\ComposerStaticInit6503970e5795e8c75f18db09788a0b40::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
