name: PHPStan

on:
  pull_request:
    branches:
      - trunk
      - develop
      - branch-*
      - feature/*
      - enhancement/*
      - fix/*

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.3']

    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none  # XDebug can be enabled here 'coverage: xdebug'
        tools: composer:v2

    - name: Install Strauss
      run: sh -c 'test -f ./bin/strauss.phar || curl -o bin/strauss.phar -L -C - https://github.com/BrianHenryIE/strauss/releases/latest/download/strauss.phar'

    - name: Install dependencies
      run: composer install --no-interaction

    - name: Run PHPStan
      run: composer run-stan -- --error-format=github

